replicaCount: 3

image:
  repository: ha
  pullPolicy: Never
  tag: "dev"

nats:
  logs: true
  config: |
    ## configuration file for nats-server
    ## https://docs.nats.io/nats-server/configuration
    listen=4222
    
    accounts {
      $SYS {
        users = [
          {
            user: "admin",
            pass: "$2a$11$DRh4C0KNbNnD8K/hb/buWe1zPxEHrLEiDmuq1Mi0rRJiH/W25Qidm"
          }
        ]
      }
    }

    jetstream {
      store_dir=/data/nats
    }
    {{if gt (int .Values.replicaCount) 1}}
    cluster {
      name: HA
      listen: 0.0.0.0:6222
      routes: [
        nats://{{ include "ha.fullname" . }}-headless:6222
      ]
    }
    {{end}}
